### ISSUE TITLE
UI Exception in Container: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by alexaryn** [aryn-ai/demo-ui#5]
This is reproducible for me in the 'docker compose' setup on branch eric-sort_improvements today.

The query is 'hi'.  Stack trace is:

Uncaught TypeError: Cannot read properties of undefined (reading 'endsWith')
    at SearchResultDocument.isPdf (Types.tsx:19:1)
    at icon (Doclist.tsx:21:1)
    at DocumentItem (Doclist.tsx:41:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)

The response data has 20 hits.  Here's hit #0:

_id: "7cbc23da-8328-11ee-8bbc-0242ac130005"
_index: "demoindex0"
_score: 0.889
_source: bbox: (4) [0.410391905357682, 0.5585842674754545, 0.4764760688893655, 0.5711600200209092]
doc_id: "7cbc23da-8328-11ee-8bbc-0242ac130005"
properties: 
  element_id: "71e54243ba447407a33473a8bc3c79f4"
  filename: ""
  filetype: "application/pdf"
  links: []
  page_number: 3
  title: "\n    A Minute with Nsort on a 32P NEC Windows Itanium2 Server"
text_representation: "Nsort [8]"
type: "Title"

**Comment by alexaryn** [comment]
What I see most obviously here, is the lack of property 'path'.

**Comment by austintlee** [comment]
```
"properties": {
      "filename": "",
      "filetype": "application/pdf",
      "page_number": 1,
      "links": [],
      "element_id": "8559fa65974d3c8291e37ebc7ca2ce56",
      "title": "\n    A Minute with Nsort on a 32P NEC Windows Itanium2 Server"
    }
```

We no longer put `url`.  Do we need to update the script to include it in the index or update the UI not to look for it?

**Comment by alexaryn** [comment]
This was an issue with ingestion not supplying 'path'.  We should still make the UI resistant, but it's not a burning priority right now.
